# Generated by Django 4.0.6 on 2022-11-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G_Block',
            fields=[
                ('Room_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Floor', models.CharField(max_length=20, null=True)),
                ('Room_Type', models.CharField(max_length=50, null=True)),
                ('Fac_Seating_capacity', models.IntegerField(null=True)),
                ('Fac_Presently_occupied', models.IntegerField(null=True)),
                ('Current_Use', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='G_Faculty_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.TextField(max_length=100, null=True)),
                ('Faculty_Dept', models.CharField(max_length=50, null=True)),
                ('Fac_Room_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G_ARModule.g_block')),
            ],
        ),
    ]
